backend:
  name: github
  repo: vignetteapp/vignette
  repository branch: master
  base_url: https://oauth.cms.vignetteapp.org/

# Hey! Don't use the IMG folder, upload it somewhere like puu.sh
media_folder: static/img

# This defines the Categories for the blog. Please use the Markdown widget everywhere as much as possible.
collections:
  - name: 'updates'
    label: 'Plaform Updates'
    folder: 'src/content/updates'
    create: true
    slug: 'updates'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }